services:
    db:
        platform: linux/x86_64
        image: mysql
        container_name: backend
        environment:
            MYSQL_ROOT_PASSWORD: backend
            MYSQL_DATABASE: backend
            MYSQL_USER: backend
            MYSQL_PASSWORD: backend
        ports:
            - "42333:3306"